import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Harakt's App",
  description: "Generated by create next app",
};

import localFont from "next/font/local";

const pokemonDP = localFont({
  src: "../../public/fonts/pokemon-dp-pro.ttf",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={pokemonDP.className}>{children}</body>
    </html>
  );
}
