import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Harakt's App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex p-4 gap-8">
          <nav>
            <Link href="/">Home</Link>
            <Link href="/ff">FFXIV</Link>
            <Link href="/ff/weather">Weather</Link>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
